name: Build Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ruby
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev zlib1g-dev
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          sudo ~/.ruby-build/install.sh
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          echo 'export PATH="/opt/hostedtoolcache/Ruby/3.1.4/x64/bin:$PATH"' >> $GITHUB_ENV
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
